-- Command System
--     NEEDs to be able to have multiple Command PCs / be hotswapable
--     Start Screen
--         At a Glace Numbers
--             Number of Bots
--             Number of Requested Bots
--             Number of Mining Sites
--         Storage System Info
--             Only for Chest Style 
--             Current Resources
--         Bot Override Screen
--             Recall all to storage
--             Update All Bots via Rednet (that way paste bin doesnt get hit with 100+ bots updateing) https://computercraft.info/wiki/Fs_(API) https://computercraft.info/wiki/Rednet_(API)
--             Stop Dispaching Bots
--             Dispach All bots (To upgrade)
--     Handheld PC View
--     AR View
